export const data = [
  {
    id: 1,
    name: "Rodrigo",
    stars: 4,
    experience: 10,
    skills: 50,
    imageUrl: "https://i.pravatar.cc/300",
  },
  {
    id: 2,
    name: "Mabel",
    stars: 4,
    experience: 10,
    skills: 50,
    imageUrl: "https://i.pravatar.cc/300",
  },
  {
    id: 3,
    name: "Gonzalo",
    stars: 23,
    experience: 40,
    skills: 40,
    imageUrl: "https://i.pravatar.cc/300",
  },
  {
    id: 4,
    name: "Lucia",
    stars: 4,
    experience: 10,
    skills: 50,
    imageUrl: "https://i.pravatar.cc/300",
  },
  {
    id: 5,
    name: "Gonzalo",
    stars: 23,
    experience: 40,
    skills: 40,
    imageUrl: "https://i.pravatar.cc/300",
  },
  {
    id: 6,
    name: "Lucia",
    stars: 4,
    experience: 10,
    skills: 50,
    imageUrl: "https://i.pravatar.cc/300",
  },
];
